<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="D:/workspace/ccop-port-match/src/main/java"
           tests="10"
           failures="1"
           errors="0"
           skipped="0"
           time="2.809">
  <properties />
            <testcase name="Test_Meg" time="0.882" classname="Test_api.Test_match_api">
                <failure type="java.lang.AssertionError"
                  message="expected [{&quot;resp_code&quot;:&quot;000094&quot;,&quot;resp_msg&quot;:&quot;重复上报&quot;}] but found [{&quot;resp_code&quot;:&quot;000000&quot;,&quot;resp_msg&quot;:&quot;SUCCESS&quot;}]"
              >
<![CDATA[java.lang.AssertionError: expected [{"resp_code":"000094","resp_msg":"重复上报"}] but found [{"resp_code":"000000","resp_msg":"SUCCESS"}]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:125)
  org.testng.Assert.assertEquals(Assert.java:178)
  org.testng.Assert.assertEquals(Assert.java:188)
  Test_api.Test_match_api.Test_Meg(Test_match_api.java:52)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.run(TestNG.java:1048)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test8" time="0.227" classname="Test_api.Test_match_api" />
                <testcase name="test2" time="0.006" classname="Test_api.Test_match_api" />
                <testcase name="test3" time="0.939" classname="Test_api.Test_match_api" />
                <testcase name="test" time="0.227" classname="Test_api.Test_match_api" />
                <testcase name="test5" time="0.000" classname="Test_api.Test_match_api" />
                <testcase name="test6" time="0.149" classname="Test_api.Test_match_api" />
                <testcase name="test7" time="0.136" classname="Test_api.Test_match_api" />
                <testcase name="test1" time="0.243" classname="Test_api.Test_match_api" />
                <testcase name="test10" time="0.000" classname="Test_api.Test_match_api" />
      
</testsuite>
